name: Releases

on:
  push:
    branches: # add more branch if necessary
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  # Enable/Uncomment if project has a test and SonarQube project
  # test-code-quality:
  #   uses: ./.github/workflows/test-code-quality.yml
  #   secrets:
  #     sonarqube-url: ${{ secrets.SONARQUBE_URL }}
  #     sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}

  build-deploy-sparklite-prod-us:
    # needs: test-code-quality
    uses: ./.github/workflows/build-deploy.yml
    with:
      env-context: Production
      build-env: prod2-us
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      s3-bucket: ${{ secrets.S3_BUCKET }}
      cloudfront-dist-id: ${{ secrets.CLOUDFRONT_DIST_ID }}


